CREATE TABLE printer_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(50) NOT NULL COMMENT '打印机名称',
    type VARCHAR(20) NOT NULL COMMENT '打印机类型（FEIE, YLY等）',
    sn VARCHAR(50) NOT NULL COMMENT '打印机编号',
    `key` VARCHAR(100) NOT NULL COMMENT '打印机密钥',
    config TEXT COMMENT '打印机配置（JSON格式）',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    remark VARCHAR(200) COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_sn (sn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='打印机配置表'; 